// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktxlpxdvwwwspnchhqor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0eGxweGR2d3d3c3BuY2hocW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjY5MjEsImV4cCI6MjA2MDEwMjkyMX0.RJh3witMrtOJDHFMEyt0IKxsqkONqfjyouMXj0xS6A0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);